# Read more about setting it up
# https://medium.com/@ljmocic/deploying-react-application-to-aws-s3-using-github-actions-85addacaeace

on:
    push:
      tags:
        - '*'
  
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Clone repository
          uses: actions/checkout@v2
        - name: Use Node.js 14.x
          uses: actions/setup-node@v1
          with:
            node-version: 14.x
        - name: Install dependencies
          run: yarn
        - name: Test
          run: yarn run test
          env:
            CI: true
        - name: Generate build
          run: yarn run build